Moved dependencies to separate file

diff --git a/setup/check_packages b/setup/check_packages
--- a/setup/check_packages
+++ b/setup/check_packages
@@ -12,29 +12,7 @@ NC='\033[0m'
 SUCCESS=0
 COMMAND_FAILURE=1
 VERSION_FAILURE=2
-
-packages=(
-	"Coreutils sort 8.1"
-	"Bash bash 3.2"
-	"Binutils ld 2.13.1"
-	"Bison bison 2.7"
-	"Diffutils diff 2.8.1"
-	"Findutils find 4.2.31"
-	"Gawk gawk 4.0.1"
-	"GCC gcc 5.2"
-	"G++ g++ 5.2"
-	"Grep grep 2.5.1a"
-	"Gzip gzip 1.3.12"
-	"M4 m4 1.4.10"
-	"Make make 4.0"
-	"Patch patch 2.5.4"
-	"Perl perl 5.8.8"
-	"Python python3 3.4"
-	"Sed sed 4.1.5"
-	"Tar tar 1.22"
-	"Texinfo texi2any 5.0"
-	"Xz xz 5.0.0"
-)
+PACKAGES_FAILURE=3
 
 exit_code=$SUCCESS
 
@@ -51,6 +29,14 @@ check_version()
 				exit_code=$VERSION_FAILURE
 		fi
 }
+
+packages_file="dependencies.txt"
+if [[ ! -f $packages_file ]]; then
+	echo -e "${RED}Could not load dependencies from $packages_file.${NC}" 1>&2
+	exit $PACKAGES_FAILURE
+fi
+
+mapfile -t packages < "$packages_file"
 
 for package in "${packages[@]}"; do
 		IFS=' ' read -r package binary min_version <<< "$package"
